name: workflow demo2

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: get secret value
      env:
        DB_USERNAME_KEY : ${{secrets.DB_USERNAME}}
      run: python test.py
